# Generated by Django 3.1.4 on 2021-03-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_bid_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='openningPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bid',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auction',
            name='imagePath',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
