# Generated by Django 3.1.4 on 2021-03-21 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210314_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='endTime',
            field=models.TimeField(default=datetime.datetime(2021, 3, 21, 10, 9, 38, 649431)),
        ),
        migrations.AlterField(
            model_name='auction',
            name='startTime',
            field=models.TimeField(default=datetime.datetime(2021, 3, 21, 10, 9, 38, 649431)),
        ),
    ]
