# Generated by Django 3.1.4 on 2021-03-21 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210321_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 21, 10, 19, 11, 626849)),
        ),
        migrations.AlterField(
            model_name='auction',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 21, 10, 19, 11, 626849)),
        ),
    ]
