# Generated by Django 3.1.4 on 2021-03-21 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210321_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 21, 10, 20, 52, 502505)),
        ),
        migrations.AlterField(
            model_name='auction',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 21, 10, 20, 52, 502505)),
        ),
    ]
