# Generated by Django 3.1.6 on 2021-03-24 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210321_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='openningPrice',
            new_name='openingPrice',
        ),
    ]
