# Generated by Django 3.1.4 on 2021-04-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210404_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(related_name='watchedBy', to='auctions.Auction'),
        ),
    ]
